class ContentWriterAgent:
    """Content Writer Agent — uses Hermes (LLM) to generate unique content.

    No templates. Every section is generated by the LLM with full context
    about the keyword, intent, tone, and specific heading.
    """

    def run(self, brief):
        from app.api import generate_content_draft

        keyword = brief.get("keyword", "")
        tone = brief.get("tone", "professional")
        word_count = brief.get("word_count_target", 1500)

        draft = generate_content_draft(
            keyword=keyword,
            brief=brief,
            tone=tone,
            word_count=word_count,
        )

        draft["title"] = brief.get("recommended_h1", keyword.title())
        draft["status"] = "Draft Generated"
        return draft
