export type CountryAirport = { code: string; name: string };

export type CountryProfile = {
  id: string; // ISO 3166-1 numeric, zero-padded to 3 digits (matches world-atlas ids)
  name: string;
  flag: string;
  capital: string;
  continent: string;
  languages: string;
  currency: string;
  greeting: string;
  culture: string;
  food: string[];
  destinations: string[];
  airports: CountryAirport[];
  funFact: string;
  // [longitude, latitude] marker for countries too small to click at 110m map scale
  marker?: [number, number];
};

export const COUNTRIES: CountryProfile[] = [
  {
    id: '608',
    name: 'Philippines',
    flag: '🇵🇭',
    capital: 'Manila',
    continent: 'Asia',
    languages: 'Filipino, English',
    currency: 'Philippine Peso (PHP)',
    greeting: 'Mabuhay!',
    culture:
      'Filipino culture blends Malay, Spanish, and American influences and is world-famous for warm hospitality. Fiestas, karaoke, close family ties, and the spirit of bayanihan (community helping) define daily life.',
    food: ['Adobo', 'Sinigang', 'Lechon'],
    destinations: ['Boracay', 'Palawan (El Nido)', 'Chocolate Hills, Bohol'],
    airports: [
      { code: 'MNL', name: 'Ninoy Aquino International Airport' },
      { code: 'CEB', name: 'Mactan-Cebu International Airport' },
    ],
    funFact: 'The Philippines has more than 7,600 islands — only about 2,000 are inhabited.',
  },
  {
    id: '392',
    name: 'Japan',
    flag: '🇯🇵',
    capital: 'Tokyo',
    continent: 'Asia',
    languages: 'Japanese',
    currency: 'Japanese Yen (JPY)',
    greeting: 'Konnichiwa!',
    culture:
      'Japan balances ancient tradition with cutting-edge modernity. Tea ceremonies, temples, and kimono coexist with bullet trains and anime, and politeness (omotenashi hospitality) shapes every guest experience.',
    food: ['Sushi', 'Ramen', 'Tempura'],
    destinations: ['Kyoto temples', 'Mount Fuji', 'Tokyo Shibuya'],
    airports: [
      { code: 'HND', name: 'Tokyo Haneda Airport' },
      { code: 'NRT', name: 'Narita International Airport' },
    ],
    funFact: 'Japan has one vending machine for roughly every 30 people.',
  },
  {
    id: '410',
    name: 'South Korea',
    flag: '🇰🇷',
    capital: 'Seoul',
    continent: 'Asia',
    languages: 'Korean',
    currency: 'South Korean Won (KRW)',
    greeting: 'Annyeonghaseyo!',
    culture:
      'South Korea mixes Confucian traditions with the global Hallyu wave of K-pop and K-dramas. Respect for elders, shared meals, and vibrant night markets are central to Korean life.',
    food: ['Kimchi', 'Bibimbap', 'Korean BBQ (Samgyeopsal)'],
    destinations: ['Gyeongbokgung Palace', 'Jeju Island', 'Busan beaches'],
    airports: [{ code: 'ICN', name: 'Incheon International Airport' }],
    funFact: 'Jeju Island is one of the New 7 Wonders of Nature.',
  },
  {
    id: '156',
    name: 'China',
    flag: '🇨🇳',
    capital: 'Beijing',
    continent: 'Asia',
    languages: 'Mandarin Chinese',
    currency: 'Renminbi / Yuan (CNY)',
    greeting: 'Nǐ hǎo!',
    culture:
      'China has over 5,000 years of continuous civilization, from calligraphy and tea culture to grand imperial architecture. Food, festivals like Lunar New Year, and family are at the heart of Chinese culture.',
    food: ['Peking Duck', 'Dim Sum', 'Hot Pot'],
    destinations: ['Great Wall of China', 'Forbidden City', 'Zhangjiajie mountains'],
    airports: [{ code: 'PEK', name: 'Beijing Capital International Airport' }],
    funFact: 'The Great Wall of China stretches over 21,000 kilometers.',
  },
  {
    id: '764',
    name: 'Thailand',
    flag: '🇹🇭',
    capital: 'Bangkok',
    continent: 'Asia',
    languages: 'Thai',
    currency: 'Thai Baht (THB)',
    greeting: 'Sawasdee!',
    culture:
      'Known as the Land of Smiles, Thailand is deeply Buddhist, with golden temples, floating markets, and the wai greeting. Street food culture and festivals like Songkran attract millions of visitors.',
    food: ['Pad Thai', 'Tom Yum Goong', 'Mango Sticky Rice'],
    destinations: ['Grand Palace, Bangkok', 'Phuket', 'Chiang Mai'],
    airports: [{ code: 'BKK', name: 'Suvarnabhumi Airport' }],
    funFact: 'Bangkok is consistently one of the most visited cities in the world.',
  },
  {
    id: '704',
    name: 'Vietnam',
    flag: '🇻🇳',
    capital: 'Hanoi',
    continent: 'Asia',
    languages: 'Vietnamese',
    currency: 'Vietnamese Dong (VND)',
    greeting: 'Xin chào!',
    culture:
      'Vietnam blends French colonial charm with rich local traditions of water puppetry, ao dai dress, and street-side coffee culture. Life happens outdoors, from motorbike-filled streets to riverside markets.',
    food: ['Pho', 'Banh Mi', 'Fresh Spring Rolls'],
    destinations: ['Ha Long Bay', 'Hoi An Ancient Town', 'Ho Chi Minh City'],
    airports: [{ code: 'SGN', name: 'Tan Son Nhat International Airport' }],
    funFact: 'Vietnam is the world’s largest exporter of robusta coffee.',
  },
  {
    id: '360',
    name: 'Indonesia',
    flag: '🇮🇩',
    capital: 'Jakarta',
    continent: 'Asia',
    languages: 'Indonesian (Bahasa Indonesia)',
    currency: 'Indonesian Rupiah (IDR)',
    greeting: 'Selamat datang!',
    culture:
      'Indonesia spans thousands of islands with hundreds of ethnic groups, from Balinese Hindu ceremonies to Javanese batik art. Gamelan music, temple festivals, and island hospitality define the archipelago.',
    food: ['Nasi Goreng', 'Satay', 'Rendang'],
    destinations: ['Bali', 'Borobudur Temple', 'Komodo National Park'],
    airports: [{ code: 'CGK', name: 'Soekarno–Hatta International Airport' }],
    funFact: 'Indonesia is the world’s largest island country with over 17,000 islands.',
  },
  {
    id: '458',
    name: 'Malaysia',
    flag: '🇲🇾',
    capital: 'Kuala Lumpur',
    continent: 'Asia',
    languages: 'Malay, English, Chinese, Tamil',
    currency: 'Malaysian Ringgit (MYR)',
    greeting: 'Selamat datang!',
    culture:
      'Malaysia is truly multicultural — Malay, Chinese, and Indian traditions share festivals, food courts, and mosques, temples, and churches side by side. “Malaysia, Truly Asia” is its famous tourism slogan.',
    food: ['Nasi Lemak', 'Laksa', 'Roti Canai'],
    destinations: ['Petronas Twin Towers', 'Langkawi', 'George Town, Penang'],
    airports: [{ code: 'KUL', name: 'Kuala Lumpur International Airport' }],
    funFact: 'The Petronas Towers were the tallest buildings in the world from 1998 to 2004.',
  },
  {
    id: '702',
    name: 'Singapore',
    flag: '🇸🇬',
    capital: 'Singapore',
    continent: 'Asia',
    languages: 'English, Malay, Mandarin, Tamil',
    currency: 'Singapore Dollar (SGD)',
    greeting: 'Welcome! (Selamat datang!)',
    culture:
      'Singapore is a gleaming city-state where Chinese, Malay, Indian, and Western cultures meet. It is famous for hawker food culture, strict cleanliness, and futuristic gardens and architecture.',
    food: ['Hainanese Chicken Rice', 'Chilli Crab', 'Laksa'],
    destinations: ['Marina Bay Sands', 'Gardens by the Bay', 'Sentosa Island'],
    airports: [{ code: 'SIN', name: 'Singapore Changi Airport' }],
    funFact: 'Changi Airport has been voted the world’s best airport more times than any other.',
    marker: [103.8198, 1.3521],
  },
  {
    id: '356',
    name: 'India',
    flag: '🇮🇳',
    capital: 'New Delhi',
    continent: 'Asia',
    languages: 'Hindi, English + 20 official languages',
    currency: 'Indian Rupee (INR)',
    greeting: 'Namaste!',
    culture:
      'India is a kaleidoscope of religions, languages, and cuisines. Bollywood, yoga, colorful festivals like Diwali and Holi, and the philosophy “Atithi Devo Bhava” (the guest is god) shape its hospitality.',
    food: ['Biryani', 'Butter Chicken', 'Masala Dosa'],
    destinations: ['Taj Mahal', 'Jaipur (Pink City)', 'Kerala backwaters'],
    airports: [{ code: 'DEL', name: 'Indira Gandhi International Airport' }],
    funFact: 'India’s rail network moves more than 20 million passengers every day.',
  },
  {
    id: '524',
    name: 'Nepal',
    flag: '🇳🇵',
    capital: 'Kathmandu',
    continent: 'Asia',
    languages: 'Nepali',
    currency: 'Nepalese Rupee (NPR)',
    greeting: 'Namaste!',
    culture:
      'Nepal is the gateway to the Himalayas, where Hindu and Buddhist traditions blend in ancient temples and prayer-flag-lined trails. Sherpa hospitality is legendary among trekkers.',
    food: ['Dal Bhat', 'Momo dumplings', 'Sel Roti'],
    destinations: ['Mount Everest Base Camp', 'Pokhara', 'Kathmandu Durbar Square'],
    airports: [{ code: 'KTM', name: 'Tribhuvan International Airport' }],
    funFact: 'Nepal’s flag is the only national flag that is not a rectangle.',
  },
  {
    id: '144',
    name: 'Sri Lanka',
    flag: '🇱🇰',
    capital: 'Sri Jayawardenepura Kotte',
    continent: 'Asia',
    languages: 'Sinhala, Tamil',
    currency: 'Sri Lankan Rupee (LKR)',
    greeting: 'Ayubowan!',
    culture:
      'Sri Lanka, the “Pearl of the Indian Ocean,” is known for Buddhist temples, tea plantations, and vibrant dance and drumming traditions. Tea culture and spice gardens are part of everyday life.',
    food: ['Rice and Curry', 'Hoppers', 'Kottu Roti'],
    destinations: ['Sigiriya Rock Fortress', 'Ella tea country', 'Galle Fort'],
    airports: [{ code: 'CMB', name: 'Bandaranaike International Airport' }],
    funFact: 'Ceylon tea from Sri Lanka is exported to more than 140 countries.',
  },
  {
    id: '116',
    name: 'Cambodia',
    flag: '🇰🇭',
    capital: 'Phnom Penh',
    continent: 'Asia',
    languages: 'Khmer',
    currency: 'Cambodian Riel (KHR)',
    greeting: 'Susadei!',
    culture:
      'Cambodia is heir to the mighty Khmer Empire, with Apsara dance, saffron-robed monks, and floating villages on the Tonlé Sap lake. Its people are known for gentle, resilient warmth.',
    food: ['Fish Amok', 'Lok Lak', 'Khmer Noodles'],
    destinations: ['Angkor Wat', 'Siem Reap', 'Koh Rong beaches'],
    airports: [{ code: 'PNH', name: 'Phnom Penh International Airport' }],
    funFact: 'Angkor Wat is the largest religious monument in the world.',
  },
  {
    id: '158',
    name: 'Taiwan',
    flag: '🇹🇼',
    capital: 'Taipei',
    continent: 'Asia',
    languages: 'Mandarin Chinese',
    currency: 'New Taiwan Dollar (TWD)',
    greeting: 'Nǐ hǎo!',
    culture:
      'Taiwan is famous for its friendly night-market culture, hot springs, and temples wreathed in incense. Bubble tea was invented here and is now a global phenomenon.',
    food: ['Beef Noodle Soup', 'Xiao Long Bao', 'Bubble Tea'],
    destinations: ['Taipei 101', 'Taroko Gorge', 'Jiufen Old Street'],
    airports: [{ code: 'TPE', name: 'Taoyuan International Airport' }],
    funFact: 'Bubble milk tea was invented in Taiwan in the 1980s.',
  },
  {
    id: '344',
    name: 'Hong Kong',
    flag: '🇭🇰',
    capital: 'Hong Kong',
    continent: 'Asia',
    languages: 'Cantonese, English',
    currency: 'Hong Kong Dollar (HKD)',
    greeting: 'Nei hou!',
    culture:
      'Hong Kong is a dazzling meeting point of East and West — dim sum teahouses beneath glass skyscrapers, traditional junks in Victoria Harbour, and one of the world’s great skylines.',
    food: ['Dim Sum', 'Roast Goose', 'Egg Tarts'],
    destinations: ['Victoria Peak', 'Tsim Sha Tsui promenade', 'Big Buddha, Lantau'],
    airports: [{ code: 'HKG', name: 'Hong Kong International Airport' }],
    funFact: 'Hong Kong has more skyscrapers than any other city on Earth.',
    marker: [114.1694, 22.3193],
  },
  {
    id: '462',
    name: 'Maldives',
    flag: '🇲🇻',
    capital: 'Malé',
    continent: 'Asia',
    languages: 'Dhivehi',
    currency: 'Maldivian Rufiyaa (MVR)',
    greeting: 'Assalaamu alaikum!',
    culture:
      'The Maldives is a nation of coral atolls famous for overwater villas and turquoise lagoons. Island life revolves around fishing, boduberu drumming, and warm island hospitality.',
    food: ['Mas Huni', 'Garudhiya fish soup', 'Fihunu Mas'],
    destinations: ['Malé', 'Baa Atoll (UNESCO)', 'Overwater resorts'],
    airports: [{ code: 'MLE', name: 'Velana International Airport' }],
    funFact: 'The Maldives is the lowest-lying country in the world.',
    marker: [73.5093, 4.1755],
  },
  {
    id: '784',
    name: 'United Arab Emirates',
    flag: '🇦🇪',
    capital: 'Abu Dhabi',
    continent: 'Asia',
    languages: 'Arabic, English widely spoken',
    currency: 'UAE Dirham (AED)',
    greeting: 'Marhaba!',
    culture:
      'The UAE fuses Bedouin desert heritage with futuristic luxury. Souks and camel racing coexist with record-breaking skyscrapers, and hospitality with Arabic coffee and dates is a treasured tradition.',
    food: ['Shawarma', 'Al Harees', 'Luqaimat'],
    destinations: ['Burj Khalifa, Dubai', 'Sheikh Zayed Grand Mosque', 'Desert safaris'],
    airports: [{ code: 'DXB', name: 'Dubai International Airport' }],
    funFact: 'Dubai International is one of the busiest airports for international passengers.',
  },
  {
    id: '634',
    name: 'Qatar',
    flag: '🇶🇦',
    capital: 'Doha',
    continent: 'Asia',
    languages: 'Arabic, English widely spoken',
    currency: 'Qatari Riyal (QAR)',
    greeting: 'Marhaba!',
    culture:
      'Qatar pairs pearl-diving heritage and falconry with striking modern museums and stadiums. The Souq Waqif and Museum of Islamic Art anchor Doha’s cultural scene.',
    food: ['Machboos', 'Karak tea', 'Luqaimat'],
    destinations: ['Souq Waqif', 'Museum of Islamic Art', 'Katara Cultural Village'],
    airports: [{ code: 'DOH', name: 'Hamad International Airport' }],
    funFact: 'Qatar hosted the first FIFA World Cup in the Middle East in 2022.',
  },
  {
    id: '682',
    name: 'Saudi Arabia',
    flag: '🇸🇦',
    capital: 'Riyadh',
    continent: 'Asia',
    languages: 'Arabic',
    currency: 'Saudi Riyal (SAR)',
    greeting: 'Assalamu alaikum!',
    culture:
      'Saudi Arabia is the birthplace of Islam and home to Mecca and Medina. Ancient Nabatean cities, vast deserts, and a fast-growing tourism scene define the kingdom today.',
    food: ['Kabsa', 'Mutabbaq', 'Arabic coffee with dates'],
    destinations: ['AlUla (Hegra)', 'Riyadh’s Diriyah', 'Jeddah Corniche'],
    airports: [{ code: 'JED', name: 'King Abdulaziz International Airport' }],
    funFact: 'AlUla’s Hegra was Saudi Arabia’s first UNESCO World Heritage Site.',
  },
  {
    id: '376',
    name: 'Israel',
    flag: '🇮🇱',
    capital: 'Jerusalem',
    continent: 'Asia',
    languages: 'Hebrew, Arabic',
    currency: 'Israeli New Shekel (ILS)',
    greeting: 'Shalom!',
    culture:
      'Israel is a crossroads of history sacred to three world religions. Ancient old-city alleys, Dead Sea spas, and a lively Mediterranean food and beach culture draw pilgrims and travelers alike.',
    food: ['Hummus', 'Falafel', 'Shakshuka'],
    destinations: ['Old City of Jerusalem', 'Dead Sea', 'Tel Aviv beaches'],
    airports: [{ code: 'TLV', name: 'Ben Gurion Airport' }],
    funFact: 'The Dead Sea shoreline is the lowest land point on Earth.',
  },
  {
    id: '792',
    name: 'Turkey',
    flag: '🇹🇷',
    capital: 'Ankara',
    continent: 'Asia',
    languages: 'Turkish',
    currency: 'Turkish Lira (TRY)',
    greeting: 'Merhaba!',
    culture:
      'Turkey bridges Europe and Asia, blending Ottoman grandeur, bazaar culture, and legendary tea and coffee hospitality. Whirling dervishes and hot-air balloons over Cappadocia are iconic sights.',
    food: ['Kebab', 'Baklava', 'Turkish Delight'],
    destinations: ['Istanbul’s Hagia Sophia', 'Cappadocia', 'Pamukkale'],
    airports: [{ code: 'IST', name: 'Istanbul Airport' }],
    funFact: 'Istanbul is the only major city located on two continents.',
  },
  {
    id: '300',
    name: 'Greece',
    flag: '🇬🇷',
    capital: 'Athens',
    continent: 'Europe',
    languages: 'Greek',
    currency: 'Euro (EUR)',
    greeting: 'Yassas!',
    culture:
      'Greece is the cradle of Western civilization — philosophy, theatre, and the Olympic Games were born here. Island life, taverna dining, and “philoxenia” (love of strangers) define Greek hospitality.',
    food: ['Moussaka', 'Souvlaki', 'Greek Salad'],
    destinations: ['Acropolis of Athens', 'Santorini', 'Mykonos'],
    airports: [{ code: 'ATH', name: 'Athens International Airport' }],
    funFact: 'Greece has more than 200 inhabited islands.',
  },
  {
    id: '380',
    name: 'Italy',
    flag: '🇮🇹',
    capital: 'Rome',
    continent: 'Europe',
    languages: 'Italian',
    currency: 'Euro (EUR)',
    greeting: 'Ciao!',
    culture:
      'Italy gave the world the Renaissance, opera, and la dolce vita. Every region has its own cuisine and dialect, and meals are celebrated as unhurried social events.',
    food: ['Pizza Napoletana', 'Pasta Carbonara', 'Gelato'],
    destinations: ['Colosseum, Rome', 'Venice canals', 'Amalfi Coast'],
    airports: [{ code: 'FCO', name: 'Rome Fiumicino Airport' }],
    funFact: 'Italy has more UNESCO World Heritage Sites than any other country.',
  },
  {
    id: '250',
    name: 'France',
    flag: '🇫🇷',
    capital: 'Paris',
    continent: 'Europe',
    languages: 'French',
    currency: 'Euro (EUR)',
    greeting: 'Bonjour!',
    culture:
      'France is synonymous with art, fashion, and gastronomy. Café culture, world-class museums, and wine regions make it the most visited country on Earth.',
    food: ['Croissant', 'Coq au Vin', 'Crème Brûlée'],
    destinations: ['Eiffel Tower', 'Louvre Museum', 'French Riviera'],
    airports: [{ code: 'CDG', name: 'Paris Charles de Gaulle Airport' }],
    funFact: 'France welcomes more international tourists than any other country.',
  },
  {
    id: '724',
    name: 'Spain',
    flag: '🇪🇸',
    capital: 'Madrid',
    continent: 'Europe',
    languages: 'Spanish',
    currency: 'Euro (EUR)',
    greeting: '¡Hola!',
    culture:
      'Spain pulses with flamenco, tapas, and late-night fiestas. Siesta rhythms, Gaudí’s architecture, and regional pride from Catalonia to Andalusia make every city distinct.',
    food: ['Paella', 'Tapas', 'Jamón Ibérico'],
    destinations: ['Sagrada Família, Barcelona', 'Alhambra, Granada', 'Ibiza'],
    airports: [{ code: 'MAD', name: 'Madrid–Barajas Airport' }],
    funFact: 'Spain is the world’s second most visited country.',
  },
  {
    id: '620',
    name: 'Portugal',
    flag: '🇵🇹',
    capital: 'Lisbon',
    continent: 'Europe',
    languages: 'Portuguese',
    currency: 'Euro (EUR)',
    greeting: 'Olá!',
    culture:
      'Portugal charms with melancholic fado music, azulejo tiles, and a seafaring legacy of great explorers. Its coastal towns and pastel cities are among Europe’s friendliest.',
    food: ['Pastéis de Nata', 'Bacalhau', 'Piri-Piri Chicken'],
    destinations: ['Lisbon’s Belém Tower', 'Porto', 'Algarve beaches'],
    airports: [{ code: 'LIS', name: 'Lisbon Humberto Delgado Airport' }],
    funFact: 'Portugal is Europe’s oldest nation-state with borders set in 1249.',
  },
  {
    id: '826',
    name: 'United Kingdom',
    flag: '🇬🇧',
    capital: 'London',
    continent: 'Europe',
    languages: 'English',
    currency: 'Pound Sterling (GBP)',
    greeting: 'Hello!',
    culture:
      'The UK blends royal pageantry, afternoon tea, and pub culture with global music and theatre. From Scottish highlands to Welsh castles, each nation has its own identity.',
    food: ['Fish and Chips', 'Sunday Roast', 'Full English Breakfast'],
    destinations: ['Big Ben & Westminster', 'Edinburgh Castle', 'Stonehenge'],
    airports: [{ code: 'LHR', name: 'London Heathrow Airport' }],
    funFact: 'London’s Heathrow is one of the busiest international airports in the world.',
  },
  {
    id: '372',
    name: 'Ireland',
    flag: '🇮🇪',
    capital: 'Dublin',
    continent: 'Europe',
    languages: 'English, Irish (Gaeilge)',
    currency: 'Euro (EUR)',
    greeting: 'Dia dhuit!',
    culture:
      'Ireland, the Emerald Isle, is famous for storytelling, traditional music sessions, and legendary pub hospitality. Ancient castles and dramatic cliffs dot its green landscapes.',
    food: ['Irish Stew', 'Soda Bread', 'Boxty'],
    destinations: ['Cliffs of Moher', 'Ring of Kerry', 'Dublin’s Temple Bar'],
    airports: [{ code: 'DUB', name: 'Dublin Airport' }],
    funFact: 'St. Patrick’s Day is celebrated in more countries than any other national festival.',
  },
  {
    id: '276',
    name: 'Germany',
    flag: '🇩🇪',
    capital: 'Berlin',
    continent: 'Europe',
    languages: 'German',
    currency: 'Euro (EUR)',
    greeting: 'Hallo!',
    culture:
      'Germany offers fairy-tale castles, Oktoberfest, and a deep legacy in music and philosophy. Efficiency and engineering pride coexist with cozy “Gemütlichkeit” beer-garden culture.',
    food: ['Bratwurst', 'Pretzels', 'Schnitzel'],
    destinations: ['Neuschwanstein Castle', 'Berlin Wall & Brandenburg Gate', 'Bavarian Alps'],
    airports: [{ code: 'FRA', name: 'Frankfurt Airport' }],
    funFact: 'Germany has more than 1,500 different types of sausages.',
  },
  {
    id: '756',
    name: 'Switzerland',
    flag: '🇨🇭',
    capital: 'Bern',
    continent: 'Europe',
    languages: 'German, French, Italian, Romansh',
    currency: 'Swiss Franc (CHF)',
    greeting: 'Grüezi!',
    culture:
      'Switzerland is a land of alpine precision — punctual trains, chocolate, cheese, and watchmaking. Four national languages share one spectacular mountain landscape.',
    food: ['Cheese Fondue', 'Raclette', 'Swiss Chocolate'],
    destinations: ['Matterhorn, Zermatt', 'Interlaken & Jungfrau', 'Lake Geneva'],
    airports: [{ code: 'ZRH', name: 'Zurich Airport' }],
    funFact: 'Switzerland has enough nuclear bunkers to shelter its entire population.',
  },
  {
    id: '040',
    name: 'Austria',
    flag: '🇦🇹',
    capital: 'Vienna',
    continent: 'Europe',
    languages: 'German',
    currency: 'Euro (EUR)',
    greeting: 'Servus!',
    culture:
      'Austria is the homeland of Mozart, imperial palaces, and Viennese coffeehouse culture. Alpine ski villages and classical concerts define its elegant charm.',
    food: ['Wiener Schnitzel', 'Sachertorte', 'Apfelstrudel'],
    destinations: ['Schönbrunn Palace', 'Salzburg', 'Hallstatt'],
    airports: [{ code: 'VIE', name: 'Vienna International Airport' }],
    funFact: 'Vienna has been ranked the world’s most liveable city multiple times.',
  },
  {
    id: '528',
    name: 'Netherlands',
    flag: '🇳🇱',
    capital: 'Amsterdam',
    continent: 'Europe',
    languages: 'Dutch',
    currency: 'Euro (EUR)',
    greeting: 'Hallo!',
    culture:
      'The Netherlands is famous for canals, cycling, tulips, and windmills. Dutch directness pairs with a long tradition of art, from Rembrandt to Van Gogh.',
    food: ['Stroopwafel', 'Dutch Cheese (Gouda)', 'Bitterballen'],
    destinations: ['Amsterdam canals', 'Keukenhof tulip gardens', 'Zaanse Schans windmills'],
    airports: [{ code: 'AMS', name: 'Amsterdam Schiphol Airport' }],
    funFact: 'There are more bicycles than people in the Netherlands.',
  },
  {
    id: '056',
    name: 'Belgium',
    flag: '🇧🇪',
    capital: 'Brussels',
    continent: 'Europe',
    languages: 'Dutch, French, German',
    currency: 'Euro (EUR)',
    greeting: 'Hallo! / Bonjour!',
    culture:
      'Belgium is the heart of Europe, known for medieval town squares, comic-strip art, and world-class chocolate and beer craftsmanship.',
    food: ['Belgian Waffles', 'Moules-Frites', 'Belgian Chocolate'],
    destinations: ['Grand Place, Brussels', 'Bruges canals', 'Antwerp'],
    airports: [{ code: 'BRU', name: 'Brussels Airport' }],
    funFact: 'Belgium produces over 220,000 tonnes of chocolate a year.',
  },
  {
    id: '203',
    name: 'Czechia',
    flag: '🇨🇿',
    capital: 'Prague',
    continent: 'Europe',
    languages: 'Czech',
    currency: 'Czech Koruna (CZK)',
    greeting: 'Ahoj!',
    culture:
      'Czechia enchants with Gothic spires, medieval astronomical clocks, and the world’s deepest beer culture. Prague’s old town is a fairy tale in stone.',
    food: ['Goulash', 'Svíčková', 'Trdelník'],
    destinations: ['Prague Castle', 'Charles Bridge', 'Český Krumlov'],
    airports: [{ code: 'PRG', name: 'Václav Havel Airport Prague' }],
    funFact: 'Czechs drink more beer per person than any other nation.',
  },
  {
    id: '616',
    name: 'Poland',
    flag: '🇵🇱',
    capital: 'Warsaw',
    continent: 'Europe',
    languages: 'Polish',
    currency: 'Polish Złoty (PLN)',
    greeting: 'Cześć!',
    culture:
      'Poland’s resilient spirit shows in its beautifully rebuilt old towns, pierogi feasts, and deep folk traditions of music and paper-cut art.',
    food: ['Pierogi', 'Żurek soup', 'Bigos'],
    destinations: ['Kraków Old Town', 'Wieliczka Salt Mine', 'Gdańsk'],
    airports: [{ code: 'WAW', name: 'Warsaw Chopin Airport' }],
    funFact: 'Kraków’s main square is the largest medieval town square in Europe.',
  },
  {
    id: '348',
    name: 'Hungary',
    flag: '🇭🇺',
    capital: 'Budapest',
    continent: 'Europe',
    languages: 'Hungarian',
    currency: 'Hungarian Forint (HUF)',
    greeting: 'Szia!',
    culture:
      'Hungary is famous for thermal bath culture, paprika-rich cuisine, and Budapest’s grand riverside architecture spanning Buda and Pest.',
    food: ['Goulash', 'Lángos', 'Chimney Cake (Kürtőskalács)'],
    destinations: ['Hungarian Parliament', 'Széchenyi Thermal Bath', 'Lake Balaton'],
    airports: [{ code: 'BUD', name: 'Budapest Ferenc Liszt Airport' }],
    funFact: 'Budapest has more thermal springs than any other capital city.',
  },
  {
    id: '191',
    name: 'Croatia',
    flag: '🇭🇷',
    capital: 'Zagreb',
    continent: 'Europe',
    languages: 'Croatian',
    currency: 'Euro (EUR)',
    greeting: 'Bok!',
    culture:
      'Croatia’s Adriatic coast is dotted with walled medieval cities and over a thousand islands. Klapa singing and seafood dining by the harbor define Dalmatian life.',
    food: ['Peka', 'Black Risotto', 'Ćevapi'],
    destinations: ['Dubrovnik Old Town', 'Plitvice Lakes', 'Hvar Island'],
    airports: [{ code: 'ZAG', name: 'Zagreb Airport' }],
    funFact: 'Dubrovnik’s walls doubled as King’s Landing in Game of Thrones.',
  },
  {
    id: '578',
    name: 'Norway',
    flag: '🇳🇴',
    capital: 'Oslo',
    continent: 'Europe',
    languages: 'Norwegian',
    currency: 'Norwegian Krone (NOK)',
    greeting: 'Hei!',
    culture:
      'Norway is a land of fjords, Viking heritage, and “friluftsliv” — the love of outdoor life. Midnight sun in summer and northern lights in winter are unforgettable.',
    food: ['Salmon (Gravlaks)', 'Brunost brown cheese', 'Fårikål'],
    destinations: ['Geirangerfjord', 'Lofoten Islands', 'Tromsø (aurora)'],
    airports: [{ code: 'OSL', name: 'Oslo Gardermoen Airport' }],
    funFact: 'Norway has the world’s longest road tunnel at 24.5 km.',
  },
  {
    id: '752',
    name: 'Sweden',
    flag: '🇸🇪',
    capital: 'Stockholm',
    continent: 'Europe',
    languages: 'Swedish',
    currency: 'Swedish Krona (SEK)',
    greeting: 'Hej!',
    culture:
      'Sweden gave the world “fika” — the sacred coffee-and-pastry break — plus ABBA, design minimalism, and midsummer flower-crown festivals.',
    food: ['Swedish Meatballs', 'Cinnamon Buns', 'Gravlax'],
    destinations: ['Stockholm’s Gamla Stan', 'Icehotel, Kiruna', 'Gothenburg archipelago'],
    airports: [{ code: 'ARN', name: 'Stockholm Arlanda Airport' }],
    funFact: 'Sweden’s Icehotel is rebuilt from scratch with new ice every winter.',
  },
  {
    id: '208',
    name: 'Denmark',
    flag: '🇩🇰',
    capital: 'Copenhagen',
    continent: 'Europe',
    languages: 'Danish',
    currency: 'Danish Krone (DKK)',
    greeting: 'Hej!',
    culture:
      'Denmark is the home of “hygge” — cozy contentment — plus Viking history, fairy tales by Hans Christian Andersen, and cutting-edge Nordic cuisine.',
    food: ['Smørrebrød', 'Danish Pastries', 'Frikadeller'],
    destinations: ['Tivoli Gardens', 'Nyhavn harbor', 'Little Mermaid statue'],
    airports: [{ code: 'CPH', name: 'Copenhagen Airport' }],
    funFact: 'LEGO was invented in Denmark — the name means “play well” in Danish.',
  },
  {
    id: '246',
    name: 'Finland',
    flag: '🇫🇮',
    capital: 'Helsinki',
    continent: 'Europe',
    languages: 'Finnish, Swedish',
    currency: 'Euro (EUR)',
    greeting: 'Hei!',
    culture:
      'Finland is the land of a thousand lakes, saunas in every home, and Santa Claus’s official hometown in Lapland. It is repeatedly ranked the happiest country in the world.',
    food: ['Karelian Pasties', 'Salmon Soup', 'Rye Bread'],
    destinations: ['Rovaniemi (Santa Claus Village)', 'Helsinki', 'Lapland aurora'],
    airports: [{ code: 'HEL', name: 'Helsinki-Vantaa Airport' }],
    funFact: 'Finland has about 3 million saunas for 5.5 million people.',
  },
  {
    id: '352',
    name: 'Iceland',
    flag: '🇮🇸',
    capital: 'Reykjavík',
    continent: 'Europe',
    languages: 'Icelandic',
    currency: 'Icelandic Króna (ISK)',
    greeting: 'Halló!',
    culture:
      'Iceland is a volcanic wonderland of geysers, glaciers, and sagas. Most Icelanders can still read thousand-year-old Viking manuscripts.',
    food: ['Icelandic Lamb Soup', 'Skyr', 'Hot Dogs (Pylsur)'],
    destinations: ['Blue Lagoon', 'Golden Circle', 'Jökulsárlón glacier lagoon'],
    airports: [{ code: 'KEF', name: 'Keflavík International Airport' }],
    funFact: 'Iceland has no mosquitoes at all.',
  },
  {
    id: '643',
    name: 'Russia',
    flag: '🇷🇺',
    capital: 'Moscow',
    continent: 'Europe/Asia',
    languages: 'Russian',
    currency: 'Russian Ruble (RUB)',
    greeting: 'Privet!',
    culture:
      'Russia spans eleven time zones with a grand tradition of ballet, literature, and onion-domed cathedrals. Tea from the samovar and banya steam baths are cultural staples.',
    food: ['Borscht', 'Pelmeni', 'Blini'],
    destinations: ['Red Square & Kremlin', 'St. Petersburg Hermitage', 'Trans-Siberian Railway'],
    airports: [{ code: 'SVO', name: 'Sheremetyevo International Airport' }],
    funFact: 'The Trans-Siberian Railway is the longest railway line in the world.',
  },
  {
    id: '818',
    name: 'Egypt',
    flag: '🇪🇬',
    capital: 'Cairo',
    continent: 'Africa',
    languages: 'Arabic',
    currency: 'Egyptian Pound (EGP)',
    greeting: 'Ahlan wa sahlan!',
    culture:
      'Egypt is home to one of humanity’s oldest civilizations — pharaohs, pyramids, and the life-giving Nile. Bustling bazaars and Nile felucca cruises continue millennia of trade and travel.',
    food: ['Koshari', 'Ful Medames', 'Molokhia'],
    destinations: ['Pyramids of Giza', 'Luxor & Valley of the Kings', 'Red Sea resorts'],
    airports: [{ code: 'CAI', name: 'Cairo International Airport' }],
    funFact: 'The Great Pyramid was the world’s tallest structure for over 3,800 years.',
  },
  {
    id: '504',
    name: 'Morocco',
    flag: '🇲🇦',
    capital: 'Rabat',
    continent: 'Africa',
    languages: 'Arabic, Berber, French',
    currency: 'Moroccan Dirham (MAD)',
    greeting: 'Salam!',
    culture:
      'Morocco dazzles with labyrinthine medinas, mint tea rituals, and Saharan camel caravans. Its riads, souks, and mosaic artistry enchant travelers.',
    food: ['Tagine', 'Couscous', 'Mint Tea'],
    destinations: ['Marrakech’s Jemaa el-Fnaa', 'Chefchaouen (Blue City)', 'Sahara Desert, Merzouga'],
    airports: [{ code: 'CMN', name: 'Casablanca Mohammed V Airport' }],
    funFact: 'Chefchaouen’s old town is painted almost entirely blue.',
  },
  {
    id: '404',
    name: 'Kenya',
    flag: '🇰🇪',
    capital: 'Nairobi',
    continent: 'Africa',
    languages: 'Swahili, English',
    currency: 'Kenyan Shilling (KES)',
    greeting: 'Jambo!',
    culture:
      'Kenya is the heart of safari tourism, home to the Maasai people and the Great Migration. “Hakuna matata” — no worries — captures its welcoming spirit.',
    food: ['Nyama Choma', 'Ugali', 'Sukuma Wiki'],
    destinations: ['Maasai Mara', 'Amboseli (Kilimanjaro views)', 'Diani Beach'],
    airports: [{ code: 'NBO', name: 'Jomo Kenyatta International Airport' }],
    funFact: 'The Great Wildebeest Migration crosses the Maasai Mara every year.',
  },
  {
    id: '710',
    name: 'South Africa',
    flag: '🇿🇦',
    capital: 'Pretoria / Cape Town / Bloemfontein',
    continent: 'Africa',
    languages: '11 official languages incl. Zulu, Xhosa, English, Afrikaans',
    currency: 'South African Rand (ZAR)',
    greeting: 'Howzit! / Sawubona!',
    culture:
      'South Africa, the “Rainbow Nation,” blends African, European, and Asian heritage. Safari, winelands, and braai barbecue culture make it a bucket-list destination.',
    food: ['Braai (barbecue)', 'Bobotie', 'Biltong'],
    destinations: ['Table Mountain', 'Kruger National Park', 'Cape Winelands'],
    airports: [{ code: 'JNB', name: 'O.R. Tambo International Airport' }],
    funFact: 'South Africa has three capital cities, one for each branch of government.',
  },
  {
    id: '840',
    name: 'United States',
    flag: '🇺🇸',
    capital: 'Washington, D.C.',
    continent: 'North America',
    languages: 'English',
    currency: 'US Dollar (USD)',
    greeting: 'Hello!',
    culture:
      'The USA is a melting pot of cultures, from Hollywood and jazz to national parks and diners. Its theme parks, road trips, and cities each offer a different world.',
    food: ['Burgers', 'BBQ Ribs', 'Apple Pie'],
    destinations: ['New York City', 'Grand Canyon', 'Walt Disney World, Orlando'],
    airports: [
      { code: 'JFK', name: 'John F. Kennedy International Airport' },
      { code: 'LAX', name: 'Los Angeles International Airport' },
    ],
    funFact: 'The US national park system covers more than 85 million acres.',
  },
  {
    id: '124',
    name: 'Canada',
    flag: '🇨🇦',
    capital: 'Ottawa',
    continent: 'North America',
    languages: 'English, French',
    currency: 'Canadian Dollar (CAD)',
    greeting: 'Hello! / Bonjour!',
    culture:
      'Canada is known for vast wilderness, multicultural cities, and legendary politeness. Maple syrup, ice hockey, and northern lights are national icons.',
    food: ['Poutine', 'Maple Syrup treats', 'Butter Tarts'],
    destinations: ['Banff National Park', 'Niagara Falls', 'Old Québec'],
    airports: [{ code: 'YYZ', name: 'Toronto Pearson International Airport' }],
    funFact: 'Canada has the longest coastline of any country in the world.',
  },
  {
    id: '484',
    name: 'Mexico',
    flag: '🇲🇽',
    capital: 'Mexico City',
    continent: 'North America',
    languages: 'Spanish',
    currency: 'Mexican Peso (MXN)',
    greeting: '¡Hola!',
    culture:
      'Mexico bursts with color — mariachi music, Day of the Dead festivities, ancient Aztec and Maya heritage, and a cuisine recognized by UNESCO as world heritage.',
    food: ['Tacos al Pastor', 'Mole', 'Chiles en Nogada'],
    destinations: ['Chichén Itzá', 'Cancún & Riviera Maya', 'Mexico City’s Zócalo'],
    airports: [{ code: 'MEX', name: 'Mexico City International Airport' }],
    funFact: 'Mexican cuisine is on UNESCO’s Intangible Cultural Heritage list.',
  },
  {
    id: '192',
    name: 'Cuba',
    flag: '🇨🇺',
    capital: 'Havana',
    continent: 'North America',
    languages: 'Spanish',
    currency: 'Cuban Peso (CUP)',
    greeting: '¡Hola!',
    culture:
      'Cuba moves to salsa and son rhythms among classic 1950s cars and pastel colonial streets. Cigars, rum, and dance are woven into island identity.',
    food: ['Ropa Vieja', 'Cuban Sandwich', 'Arroz con Frijoles'],
    destinations: ['Old Havana', 'Varadero Beach', 'Viñales Valley'],
    airports: [{ code: 'HAV', name: 'José Martí International Airport' }],
    funFact: 'Classic American cars from the 1950s still cruise Havana’s streets.',
  },
  {
    id: '076',
    name: 'Brazil',
    flag: '🇧🇷',
    capital: 'Brasília',
    continent: 'South America',
    languages: 'Portuguese',
    currency: 'Brazilian Real (BRL)',
    greeting: 'Olá!',
    culture:
      'Brazil is samba, carnival, football, and the Amazon. Its joyful beach culture and the world’s biggest carnival parade in Rio define South American festivity.',
    food: ['Feijoada', 'Pão de Queijo', 'Churrasco'],
    destinations: ['Christ the Redeemer, Rio', 'Iguazu Falls', 'Amazon Rainforest'],
    airports: [{ code: 'GRU', name: 'São Paulo–Guarulhos Airport' }],
    funFact: 'Rio’s Carnival attracts around two million people per day on the streets.',
  },
  {
    id: '604',
    name: 'Peru',
    flag: '🇵🇪',
    capital: 'Lima',
    continent: 'South America',
    languages: 'Spanish, Quechua, Aymara',
    currency: 'Peruvian Sol (PEN)',
    greeting: '¡Hola!',
    culture:
      'Peru is the heart of the ancient Inca Empire, where Andean traditions, weaving, and pan-flute music live on. Lima is celebrated as a world food capital.',
    food: ['Ceviche', 'Lomo Saltado', 'Ají de Gallina'],
    destinations: ['Machu Picchu', 'Cusco & Sacred Valley', 'Lake Titicaca'],
    airports: [{ code: 'LIM', name: 'Jorge Chávez International Airport' }],
    funFact: 'Peru grows more than 4,000 native varieties of potato.',
  },
  {
    id: '032',
    name: 'Argentina',
    flag: '🇦🇷',
    capital: 'Buenos Aires',
    continent: 'South America',
    languages: 'Spanish',
    currency: 'Argentine Peso (ARS)',
    greeting: '¡Hola!',
    culture:
      'Argentina is the birthplace of tango, legendary steakhouse asado culture, and passionate football. Buenos Aires is often called the “Paris of South America.”',
    food: ['Asado (steak)', 'Empanadas', 'Dulce de Leche'],
    destinations: ['Iguazú Falls', 'Patagonia (Perito Moreno)', 'Buenos Aires La Boca'],
    airports: [{ code: 'EZE', name: 'Ministro Pistarini (Ezeiza) Airport' }],
    funFact: 'Tango was declared a UNESCO Intangible Cultural Heritage.',
  },
  {
    id: '152',
    name: 'Chile',
    flag: '🇨🇱',
    capital: 'Santiago',
    continent: 'South America',
    languages: 'Spanish',
    currency: 'Chilean Peso (CLP)',
    greeting: '¡Hola!',
    culture:
      'Chile stretches from the driest desert on Earth to Patagonian glaciers. Poetry (Neruda), wine valleys, and star-gazing observatories are national treasures.',
    food: ['Empanadas de Pino', 'Pastel de Choclo', 'Completo'],
    destinations: ['Atacama Desert', 'Torres del Paine', 'Easter Island'],
    airports: [{ code: 'SCL', name: 'Santiago Arturo Merino Benítez Airport' }],
    funFact: 'Easter Island’s moai statues were carved between 1250 and 1500 CE.',
  },
  {
    id: '170',
    name: 'Colombia',
    flag: '🇨🇴',
    capital: 'Bogotá',
    continent: 'South America',
    languages: 'Spanish',
    currency: 'Colombian Peso (COP)',
    greeting: '¡Hola!',
    culture:
      'Colombia is the land of coffee, cumbia, and colorful colonial towns. Its Caribbean coast, Andean peaks, and Amazon jungle pack three worlds into one country.',
    food: ['Arepas', 'Bandeja Paisa', 'Ajiaco'],
    destinations: ['Cartagena Old City', 'Coffee Triangle', 'Tayrona National Park'],
    airports: [{ code: 'BOG', name: 'El Dorado International Airport' }],
    funFact: 'Colombia is one of the most biodiverse countries on the planet.',
  },
  {
    id: '036',
    name: 'Australia',
    flag: '🇦🇺',
    capital: 'Canberra',
    continent: 'Oceania',
    languages: 'English',
    currency: 'Australian Dollar (AUD)',
    greeting: 'G’day mate!',
    culture:
      'Australia pairs laid-back beach culture with the world’s oldest living culture — Aboriginal traditions going back 60,000+ years. Surfing, barbecues, and unique wildlife define Aussie life.',
    food: ['Meat Pie', 'Vegemite on Toast', 'Lamingtons'],
    destinations: ['Sydney Opera House', 'Great Barrier Reef', 'Uluru'],
    airports: [{ code: 'SYD', name: 'Sydney Kingsford Smith Airport' }],
    funFact: 'The Great Barrier Reef is the largest living structure on Earth.',
  },
  {
    id: '554',
    name: 'New Zealand',
    flag: '🇳🇿',
    capital: 'Wellington',
    continent: 'Oceania',
    languages: 'English, Māori',
    currency: 'New Zealand Dollar (NZD)',
    greeting: 'Kia ora!',
    culture:
      'New Zealand blends Māori heritage — haka, marae, and manaakitanga hospitality — with epic adventure tourism. Its landscapes starred as Middle-earth in The Lord of the Rings.',
    food: ['Hāngī', 'Pavlova', 'Green-lipped Mussels'],
    destinations: ['Milford Sound', 'Queenstown', 'Hobbiton, Matamata'],
    airports: [{ code: 'AKL', name: 'Auckland Airport' }],
    funFact: 'Queenstown is known as the adventure capital of the world.',
  },
  {
    id: '242',
    name: 'Fiji',
    flag: '🇫🇯',
    capital: 'Suva',
    continent: 'Oceania',
    languages: 'Fijian, English, Fiji Hindi',
    currency: 'Fijian Dollar (FJD)',
    greeting: 'Bula!',
    culture:
      'Fiji’s 300+ islands are famous for the warmest welcome in the Pacific — the joyful “Bula!” greeting, kava ceremonies, and firewalking traditions.',
    food: ['Kokoda (Fijian ceviche)', 'Lovo feast', 'Cassava'],
    destinations: ['Mamanuca Islands', 'Coral Coast', 'Yasawa Islands'],
    airports: [{ code: 'NAN', name: 'Nadi International Airport' }],
    funFact: 'Fiji sits right next to the 180° meridian — one of the first places to greet each new day.',
  },
];

const countryById = new Map(COUNTRIES.map((country) => [country.id, country]));

export function getCountryById(id: string | number | undefined | null) {
  if (id === undefined || id === null) return undefined;
  return countryById.get(String(id).padStart(3, '0'));
}

export const MAP_MARKERS = COUNTRIES.filter(
  (country): country is CountryProfile & { marker: [number, number] } => Boolean(country.marker),
);

// Countries that are large enough to click on the 110m world map (used by the map game)
export const CLICKABLE_COUNTRIES = COUNTRIES.filter((country) => !country.marker);

export const ALL_AIRPORTS = COUNTRIES.flatMap((country) =>
  country.airports.map((airport) => ({ ...airport, country: country.name, flag: country.flag })),
);
